Vagrant.configure("2") do |config|
config.vm.define "web.lab" do |web|
 web.vm.box = "sbeliakou/centos"
 web.vm.hostname = "web.lab"
 web.vm.network :private_network, ip: "192.168.56.11"
 web.vm.provision "shell", path: "webscript.sh"
 web.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  end
end

config.vm.define "tomcat1.lab" do |tomcat1|
 tomcat1.vm.box = "sbeliakou/centos"
 tomcat1.vm.hostname = "tomcat1.lab"
 tomcat1.vm.network :private_network, ip: "192.168.56.111"
 tomcat1.vm.provision "shell", path: "tomcatscript.sh"
 tomcat1.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end

config.vm.define "tomcat2.lab" do |tomcat2|
 tomcat2.vm.box = "sbeliakou/centos"
 tomcat2.vm.hostname = "tomcat2.lab"
 tomcat2.vm.network :private_network, ip: "192.168.56.222"
 tomcat2.vm.provision "shell", path: "tomcatscript.sh"
 tomcat2.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
end

