Vagrant.configure("2") do |config|
config.vm.define "nginx" do |nginx|
 nginx.vm.box = "sbeliakou/centos"
 nginx.vm.hostname = "nginx"
 nginx.vm.network :private_network, ip: "192.168.56.222"
 nginx.vm.provision "shell", path: "nginx.sh"
 nginx.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
end
