Vagrant.configure("2") do |config|
config.vm.define "server" do |server|
 server.vm.box = "sbeliakou/centos"
 server.vm.hostname = "server"
 server.vm.network :private_network, ip: "192.168.56.111"
 server.vm.provision "shell", path: "server.sh"
 server.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
config.vm.define "agent" do |agent|
 agent.vm.box = "sbeliakou/centos"
 agent.vm.hostname = "agent"
 agent.vm.network :private_network, ip: "192.168.56.222"
 agent.vm.provision "shell", path: "agent.sh"
 agent.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
end
