Vagrant.configure("2") do |config|
config.vm.define "web1" do |web1|
 web1.vm.box = "sbeliakou/centos"
 web1.vm.hostname = "nginx"
 web1.vm.network :private_network, ip: "192.168.56.111"
 web1.vm.provision "shell", path: "nginx_1.sh"
 web1.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
config.vm.define "web2" do |web2|
 web2.vm.box = "sbeliakou/centos"
 web2.vm.hostname = "web2"
 web2.vm.network :private_network, ip: "192.168.56.222"
 web2.vm.provision "shell", path: "nginx_2.sh"
 web2.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
config.vm.define "lb" do |lb|
 lb.vm.box = "sbeliakou/centos"
 lb.vm.hostname = "lb"
 lb.vm.network :private_network, ip: "192.168.56.100"
 lb.vm.provision "shell", path: "nginx_lb.sh"
 lb.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  end
end
end
